py37:
  image: python:3.7

  services:
  - postgres

  variables:
    DATABASE_URL: postgresql://quart_db:quart_db@postgres:5432/quart_db
    POSTGRES_DB: quart_db
    POSTGRES_USER: quart_db
    POSTGRES_PASSWORD: quart_db
    POSTGRES_HOST_AUTH_METHOD: "trust"

  script:
  - pip install tox
  - tox -e py37

py38:
  image: python:3.8

  services:
  - postgres

  variables:
    DATABASE_URL: postgresql://quart_db:quart_db@postgres:5432/quart_db
    POSTGRES_DB: quart_db
    POSTGRES_USER: quart_db
    POSTGRES_PASSWORD: quart_db
    POSTGRES_HOST_AUTH_METHOD: "trust"

  script:
  - pip install tox
  - tox -e py38

py39:
  image: python:3.9

  services:
  - postgres

  variables:
    DATABASE_URL: postgresql://quart_db:quart_db@postgres:5432/quart_db
    POSTGRES_DB: quart_db
    POSTGRES_USER: quart_db
    POSTGRES_PASSWORD: quart_db
    POSTGRES_HOST_AUTH_METHOD: "trust"

  script:
  - pip install tox
  - tox -e py39

py310:
  image: python:3.10

  services:
  - postgres

  variables:
    DATABASE_URL: postgresql://quart_db:quart_db@postgres:5432/quart_db
    POSTGRES_DB: quart_db
    POSTGRES_USER: quart_db
    POSTGRES_PASSWORD: quart_db
    POSTGRES_HOST_AUTH_METHOD: "trust"

  script:
  - pip install tox
  - tox -e docs,format,mypy,py310,pep8,package

pages:
  image: python:3.10
  script:
  - pip install . sphinx pydata-sphinx-theme
  - rm -rf docs/source && sphinx-apidoc -e -f -o docs/reference/source/ src/quart_db/
  - cd docs/ && make html && cd ../
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
